#theme: jekyll-theme-hacker
repository: sorskoot/MakeCodeMinecraft
plugins:
  - jekyll-paginate
  - kramdown
  - jemoji

baseurl: ""
paginate: 5
paginate_path: "page:num"

# Build settings
sass:
  sass_dir: _sass
  style: :compressed
markdown: kramdown
exclude:
  - README.md